[package]
name = "tablers"
version = "0.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "tablers"
crate-type = ["cdylib"]

[dependencies]
once_cell = "1.21.3"
pdfium-render = "0.8.37"
pyo3 = "0.27.0"
